#YAML
use_instrument_weight_estimates: False
use_forecast_weight_estimates: False
percentage_vol_target: 50
notional_trading_capital: 2000

base_currency: "USDT"
trading_rules:
  ewmac4:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
  ewmac6:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 6
         Lslow: 24
  ewmac8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
instruments: [BTC-USDT-SWAP,  ETH-USDT-SWAP, ]
instrument_div_multiplier: 1
instrument_weights:
  BTC-USDT-SWAP: 0.5
  ETH-USDT-SWAP: 0.5
forecast_weights:
  BTC-USDT-SWAP:
    ewmac4: 0.2
    ewmac6: 0.15
    ewmac8: 0.15
    breakout10: 0.5
  ETH-USDT-SWAP:
    ewmac4: 0.2
    ewmac6: 0.15
    ewmac8: 0.15
    breakout10: 0.5
forecast_div_multiplier: 1

