#YAML
percentage_vol_target: 25
notional_trading_capital: 100_0000
base_currency: "USD"
trading_rules:
  ewmac32:
     function: systems.provided.rules.ewmac.ewmac_forecast_with_defaults
     other_args: 
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
forecast_weights:
     ewmac32: 1
forecast_div_multiplier: 1
instrument_weights:
     BRENT-LAST: .33
     COPPER: .33
     GOLD: .33
instrument_div_multiplier: 1.5
