#YAML
percentage_vol_target: 12
notional_trading_capital: 500_000
base_currency: "UST"
trading_rules:
  ewmac8:
     function: systems.provided.rules.ewmac.ewmac_forecast_with_defaults
     data: data.daily_prices
     other_args: 
         Lfast: 8
         Lslow: 32
    #  forecast_scalar: 5.3
  breakout:
     function: systems.provided.rules.breakout.breakout
     data: data.daily_prices
     other_args: 
        lookback: 30

use_forecast_scale_estimates: True
#
forecast_scalar_estimate:
   pool_instruments: True

forecast_weights:
     ewmac8: 0.5
     breakout: 0.5
forecast_div_multiplier: 1
use_instrument_weight_estimates: True
# instrument_weights:
#      BITFINEX-BTCUST: 0.5
#      BITFINEX-ETHUST: 0.5
instrument_div_multiplier: 1
